### ISSUE TITLE
[需求]未使用的变量应该提示

### ISSUE THREAD

**Issue by Nbsaw** [KasumiUtako/lidis-client#2]
https://github.com/KasumiUtako/lidis-client/blob/b217197d0c90a451e0ef18406613e8f027df8b2e/src/store/mutations.ts#L1

這一行的`Mutation`。上下文中都未被使用到。应该有个提示。然鹅实际上并没有。

**Comment by fimars** [comment]
@Nbsaw lidis-client这个项目配置的tslint规则很弱，实际上并没有这条规则。
